### ISSUE TITLE
Make a downloadable binary available

### ISSUE THREAD

**Issue by toolness** [18F/cg-fake-uaa#2]
For folks who just want to use the tool and don't have Go installed.

**Comment by jcscottiii** [comment]
Nice! A tool we use for compliance-masonry is `goxc`.
https://github.com/opencontrol/compliance-masonry/blob/master/CONTRIBUTING.md#creating-binaries

And automatically uploads to the releases page.

![image](https://cloud.githubusercontent.com/assets/7788930/16837980/b4c8374e-4994-11e6-83d6-d339118548c1.png)
