### ISSUE TITLE
Wrong documentation? ./fake-cloud.gov does not exist

### ISSUE THREAD

**Issue by eddietejeda** [18F/cg-fake-uaa#21]
The documentation says to run `./fake-cloud.gov` but the binary is called `./cg-fake-uaa`. I am assuming this is a mistake in the doc and not missing binary. Correct?

**Comment by sharms** [comment]
Hi thank you for the report! You are right, it looks like we migrated to a new name but didn't update the README.  Does PR #22 solve this for you?

**Comment by toolness** [comment]
Wow, thanks for reporting this @eddietejeda and for the super quick fix @sharms and @LinuxBozo :)
