### ISSUE TITLE
Add vendoring support.

### ISSUE THREAD

**Issue by jcscottiii** [18F/cg-fake-uaa#4]
To ensure a developer gets the same commits for the external dependencies, using a vendoring tool would help.

A recommended tool is `glide`
https://github.com/Masterminds/glide

Heads-up
With any vendoring tool for Go versions >=1.6, it will add a vendor folder to your project.
This will break all of your recursive commands lol. `go test ./...` for example because it will then start testing your tests dependencies which is okay **BUT** it will continue down the rabbit hole and try to start to test your dependencies's dependencies which will break probably because Go vendoring is not standardized yet. 

To the rescue with `glide`:
You can avoid this with `go test $(glide nv)` which glide will just get all of your packages and ignore the vendored ones. (hence nv == nonvendor)

**Comment by toolness** [comment]
Cool, I definitely like the vendoring idea, coming from nodejs-land :)

In my case could I just do `go test *.go` since all the files are in the root directory? Or alternatively, what if I made a `src` directory that contained all my go files, so I could do `go test src` or something?

**Comment by jcscottiii** [comment]
You'll want to use the former for now. :)

In terms of folder names (which become package names), Go calls for the folder names to be used to indicate function `compute` and not just containers.

More on https://blog.golang.org/package-names
