### ISSUE TITLE
As a Go developer, would like clear instructions on how to use in my tests

### ISSUE THREAD

**Issue by jcscottiii** [18F/cg-fake-uaa#7]
cg-deck would benefit from this.
Instead of me downloading a binary, if a Go developer could just import the library and use `NewServerHandler`, that would nice. (I'm sure this could happen already just the docs are needed)

**Comment by toolness** [comment]
Oh nice, I hadn't even thought of go programs using this code directly as a library!

Are there any best practices on documenting a function like `NewServerHandler`, and its associated `ServerConfig` data structure? Should I just put something in the README, or should I use this funky [`godoc`](http://godoc.org/golang.org/x/tools/cmd/godoc) tool?

**Comment by jcscottiii** [comment]
You can just put comments on the function.

``` go
// NewServerHandler is .... (you must start the comment with the name of the function itself)
func NewServerHandler() {
}
```

You can also document the whole package too.

More details on both: https://blog.golang.org/godoc-documenting-go-code
