### ISSUE TITLE
config could be nil

### ISSUE THREAD

**Issue by jcscottiii** [18F/cg-fake-uaa#9]
From an outside view, if I use https://github.com/18F/cg-fake-uaa/blob/master/server.go#L13, but accidentally send in a nil config, things could get bad

It would be hard to check for config there so I guess you could check it in places that actually use it. Example in this function:
https://github.com/18F/cg-fake-uaa/blob/master/authorize.go#L50

**Comment by toolness** [comment]
Thanks! Hmm, I'm unclear on why it'd be hard to check for config in `NewServerHandler`?  Couldn't I just check to see if it's nil and panic with a helpful error message if so?

I don't suppose there's any way to ensure at compile-time that config isn't nil?

**Comment by jcscottiii** [comment]
not a compile time but we can add a check at the beginning of the function.
Change the function from:

``` go
func NewServerHandler(config *ServerConfig) func(http.ResponseWriter, *http.Request) {
    return func(w http.ResponseWriter, r *http.Request) {
        baseHandler(config, w, r)
    }
}
```

to

``` go
func NewServerHandler(config *ServerConfig) (func(http.ResponseWriter, *http.Request), error) {
    if err := checkConfig(config); err != nil {
        return nil, err
    }
        return func(w http.ResponseWriter, r *http.Request) {
        baseHandler(config, w, r)
    }, nil
}
```

I created something similar to show
https://play.golang.org/p/mMY0U7lKcX
